[COS-2761] Validación de flujo 3DS para comercios que tokenizan por API
ksh-js-sdk-dev/kushki-js-sdk pull request #203
Opened 2024-03-20 20:44 UTC by stevenaizaga

2024-03-20 22:07 UTC, LuisCuascota requested changes

2024-03-21 16:28 UTC, LuisCuascota requested changes

2024-03-21 16:28 UTC, LuisCuascota commented on src/module/AntiFraud.ts
> + * Function to request a secure initialization of Cardinal 3DS or Cardinal 3DS Sandbox depending on the merchant settings.
Function to request a secure initialization of Cardinal 3DS or Sandbox 3DS  depending on the merchant settings.

2024-03-21 16:28 UTC, LuisCuascota commented on src/module/AntiFraud.ts
> + * @param {SecureInitRequest} secureInitRequest - You must define this object in order to request the initialization of Cardinal 3DS.
You must define this object in order to request the initialization of 3DS

2024-03-21 16:28 UTC, LuisCuascota commented on src/module/AntiFraud.ts
> + *  - if the param: `secureInitRequest` does not have the needed card length (cardNumber < 6 or cardNumber > 19)  {@link ERRORS | ERRORS.E016}
Tambien puede dar error si el request del jwt falla, ese error tambien colocar

2024-03-21 16:30 UTC, paosteph requested changes

2024-03-21 16:30 UTC, paosteph commented on showcase/src/containers/AntiFraud/AntiFraud.tsx
> +    "d6b3e17702e64d85b812c089e24a1ca1"
porque se deja quemada la data? es para un demo?

2024-03-21 16:30 UTC, paosteph commented on showcase/src/containers/AntiFraud/AntiFraud.tsx
> +        "https://api-uat.kushkipagos.com/card/v1/tokens",
porque se deja quemada la url? se puede usar constantes en su lugar para los diferentes ambientes?

2024-03-21 16:30 UTC, paosteph commented on showcase/src/containers/AntiFraud/AntiFraud.tsx
> +  const onTokenRequest = async () => {
no sería: onRequestToken ?

2024-03-21 16:30 UTC, paosteph commented on showcase/src/containers/AntiFraud/AntiFraud.tsx
> +  const on3DSValidation = async () => {
onHandle3DSValidation ?

2024-03-21 16:30 UTC, paosteph commented on showcase/src/containers/AntiFraud/AntiFraud.tsx
> +    setResponse("");
estas dos acciones colocar en una función que sea "resetForm" o algo similar y llamar en todos los apratados donde se llaman estas dos acciones
```
setDisableButton(true);
setResponse("");
```

2024-03-21 16:30 UTC, paosteph commented on showcase/src/containers/AntiFraud/AntiFraud.tsx
> +    let isValid: boolean = false;
mejorar el nombre de "isValid" , que es lo válido ?

2024-03-21 16:30 UTC, paosteph commented on showcase/src/containers/AntiFraud/AntiFraud.tsx
> +          <h3 className={"titleDemo"}>AntiFraud Auth</h3>
igual que a Santi, estandarizar los nombres está mezclado kebab-case con keba/camel-case en varias partes, revisar cambios de Santi

2024-03-21 16:30 UTC, paosteph commented on showcase/src/containers/AntiFraud/AntiFraud.tsx
> +            label={"Numero de tarjeta"}
tilde: Número

2024-03-21 16:30 UTC, paosteph commented on showcase/src/containers/AntiFraud/AntiFraud.tsx
> +            Request 3DS Valdiation
Valdiation -> Validación

2024-03-21 16:30 UTC, paosteph commented on src/libs/genversion/version.ts
> +export const version = "1.1.0-14523.1";
si estamos igualados al release?? esto ya actualizó Santi en su PR

2024-03-21 16:30 UTC, paosteph commented on src/schema/secure_init_request.json
> +  "description": "@public Contains the card number",
no es un request? la descripción no se relaciona al nombre del schema

2024-03-21 16:30 UTC, paosteph commented on src/service/AntiFraudService.spec.ts
> +    it("should return error when card number is too short", async () => {
que longitud de tarjeta es too short?

2024-03-21 16:30 UTC, paosteph commented on src/service/AntiFraudService.spec.ts
> +    it("should return error when card number is too long", async () => {
que longitud de tarjeta es too long?

2024-03-21 16:30 UTC, paosteph commented on src/service/AntiFraudService.spec.ts
> +    it("should return validate3DS success", async () => {
retorna true o false y cuando?

2024-03-21 16:30 UTC, paosteph commented on src/service/AntiFraudService.spec.ts
> +        expect(get(error, "code")).toBe("E005");
en el nombre del expect dice que retornará E012

2024-03-21 16:30 UTC, paosteph commented on src/service/AntiFraudService.spec.ts
> +    it("should return error E012 when security is undefined in request", async () => {
"when security is undefined" security se refiere al objeto request ?

2024-03-21 16:30 UTC, paosteph commented on src/service/AntiFraudService.spec.ts
> +    it("should return isValid when sandbox is enabled and paReq is equal to sandbox", async () => {
isValid retorna true o false?

2024-03-21 16:30 UTC, paosteph commented on src/service/AntiFraudService.spec.ts
> +    it("should return isValid when sandbox is enabled, paReq is equal to sandbox and secure otp response code is 3DS000", async () => {
isValid retorna true o false?

2024-03-21 16:30 UTC, paosteph commented on src/service/AntiFraudService.spec.ts
> +    it("should return isValid when sandbox is disabled and paReq is equal to sandbox", async () => {
isValid retorna true o false?

2024-03-21 16:30 UTC, paosteph commented on src/service/AntiFraudService.spec.ts
> +        expect(get(error, "code")).toBe("E005");
el código no hace match con el del nombre del test

2024-03-21 16:30 UTC, paosteph commented on src/utils/3DSUtils.ts
> +      : accountNumber; // bin 8
eliminar comment y en tal caso dar un nombre más representativo ala const

2024-03-21 16:30 UTC, paosteph commented on src/utils/3DSUtils.spec.ts
> +    it("should return jwt for merchant with cardinal 3DS with generated bin for card subscription", async () => {
falta when

2024-03-21 16:30 UTC, paosteph commented on src/utils/3DSUtils.spec.ts
> +    it("should return jwt for merchant with sandbox 3DS", async () => {
falta when

2024-03-21 18:22 UTC, stevenaizaga commented on src/utils/3DSUtils.spec.ts
> +    it("should return jwt for merchant with cardinal 3DS with generated bin for card subscription", async () => {
esto es del Santi jaja ya en el merge del release se corrige

2024-03-21 20:37 UTC, LuisCuascota requested changes

2024-03-21 20:37 UTC, LuisCuascota commented on README.md
> +Before using [payment card token](#get-a-payment-card-token) to create a token. Kushki securely communicates with Cardinal 3DS to validate the card number in the checkout process.
aqui seria de colocar el link a la documentacion de la api de tokens, y especificar que se utiliza para los comercios que tokenizan por API

2024-03-21 20:37 UTC, LuisCuascota commented on README.md
> +After using [payment card token](#get-a-payment-card-token) to create a token. Kushki securely communicates with Cardinal 3DS to validate the transaction in the checkout process.
lo mismo, linkear a la doc de la api de kushki

2024-03-21 20:37 UTC, LuisCuascota commented on README.md
> +This method will return a token response body when the validation is successful. More details [Click here](https://ksh-js-sdk-dev.github.io/kushki-js-sdk/docs/functions/Antifraud.requestValidate3DS.h
especificar que el input es lo que se obtiene de la api de token y que antes de ello debe hacer el secureInit

2024-03-21 22:05 UTC, paosteph requested changes

2024-03-21 22:05 UTC, paosteph commented on src/service/AntiFraudService.spec.ts
> +    it("should return error E012 when cardinal action code is equal to FAILURE", async () => {
el código del expect dice E005

2024-03-21 22:05 UTC, paosteph commented on src/service/AntiFraudService.ts
> +    if (cardTokenResponse.security === undefined)
sería mejor si se usa isNil() para validar si es null o undefined

2024-03-21 22:05 UTC, paosteph commented on src/service/AntiFraudService.ts
> +  private static _getBinFromCreditCardNumber(value: string): string {
falta un espacio eentre funcs

2024-03-21 22:05 UTC, paosteph commented on src/service/AntiFraudService.ts
> +    if (request.card.number.length < 6 || request.card.number.length > 19)
el 6 y el 19 colocar  mejor en una constante externa que los describa, (magic number)

2024-03-21 22:43 UTC, paosteph approved these changes

2024-03-21 22:45 UTC, merged