feat(COS-2768): Add requestInitAntiFraud method and Sift script initi…
ksh-js-sdk-dev/kushki-js-sdk pull request #224
Opened 2024-06-10 22:17 UTC by LuisCuascota

…alization

2024-06-10 22:25 UTC, stevenaizaga requested changes

2024-06-10 22:25 UTC, stevenaizaga commented on src/provider/SiftScienceProvider.spec.ts
> +    it("should throws error when merchant have sift disabled", async () => {
aca ponle como 
should throw an error when merchant have sift disabled

2024-06-10 22:25 UTC, stevenaizaga commented on src/provider/SiftScienceProvider.spec.ts
> +    it("should throw error when load script fails", async () => {
lo mismo aca

2024-06-10 22:33 UTC, diego-beltran-kushki commented on src/module/AntiFraud.ts
> + *       console.log(response);
Estos console.log están bien q se queden ?

2024-06-10 22:49 UTC, LuisCuascota commented on src/module/AntiFraud.ts
> + *       console.log(response);
Si, son parte del ejemplo e la documentacion

2024-06-11 14:07 UTC, stevenaizaga approved these changes

2024-06-11 14:08 UTC, diego-beltran-kushki approved these changes

2024-06-11 15:10 UTC, washington-paredes approved these changes

2024-06-11 15:10 UTC, merged